// ─── PDF Case Export (using browser print) ──────────────────────────
export function exportCasePDF(patient, dxResult, txResult, doctor) {
  const win = window.open('', '_blank', 'width=800,height=1000')
  const ge = typeof patient.generalExam === 'object' ? patient.generalExam : {}
  const geParts = []
  if (ge.built) geParts.push(`Built: ${ge.built}`)
  if (ge.pallor) geParts.push(`Pallor: ${ge.pallor}`)
  if (ge.jaundice) geParts.push(`Jaundice: ${ge.jaundice}`)
  if (ge.cyanosis) geParts.push(`Cyanosis: ${ge.cyanosis}`)
  if (ge.edema) geParts.push(`Edema: ${ge.edema}`)
  if (ge.jvp) geParts.push(`JVP: ${ge.jvp}`)

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Case Summary - ${patient.name}</title>
<style>
  body { font-family: 'Inter', Arial, sans-serif; color: #111; max-width: 700px; margin: 0 auto; padding: 40px; font-size: 13px; line-height: 1.6; }
  h1 { font-size: 22px; border-bottom: 2px solid #111; padding-bottom: 8px; }
  h2 { font-size: 15px; color: #333; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 16px; }
  .label { color: #666; font-size: 11px; text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { padding: 6px 8px; text-align: left; border-bottom: 1px solid #eee; font-size: 12px; }
  th { background: #f5f5f5; font-weight: 600; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }
  .badge-high { background: #dcfce7; color: #16a34a; }
  .badge-medium { background: #fef3c7; color: #d97706; }
  .badge-low { background: #fee2e2; color: #dc2626; }
  .footer { margin-top: 40px; text-align: right; font-size: 11px; color: #999; }
  .sig { margin-top: 60px; text-align: right; }
  .sig-line { border-top: 1px solid #111; width: 200px; margin-left: auto; margin-bottom: 4px; }
  @media print { body { padding: 20px; } }
</style></head><body>
<h1>Case Summary</h1>
<div class="grid">
  <div><span class="label">Patient:</span> ${patient.name || '—'}</div>
  <div><span class="label">Age/Sex:</span> ${patient.age || '—'} / ${patient.sex || '—'}</div>
  <div><span class="label">Weight:</span> ${patient.weight ? patient.weight + ' kg' : '—'}</div>
  <div><span class="label">Date:</span> ${new Date().toLocaleDateString()}</div>
  <div><span class="label">BP:</span> ${patient.bp || '—'}</div>
  <div><span class="label">Pulse:</span> ${patient.pulse || '—'}/min</div>
  <div><span class="label">Temp:</span> ${patient.temp || '—'}°F</div>
  <div><span class="label">SpO2:</span> ${patient.spo2 || '—'}%</div>
</div>
<h2>Chief Complaints</h2><p>${patient.complaints || '—'}</p>
<h2>History</h2>
<p><strong>Past:</strong> ${patient.pastHistory || '—'}</p>
<p><strong>Drugs:</strong> ${patient.drugHistory || '—'}</p>
<p><strong>Investigations:</strong> ${patient.investigations || '—'}</p>
<p><strong>Social/Family:</strong> ${patient.socialFamily || '—'}</p>
<h2>General Examination</h2><p>${geParts.join(', ') || '—'}</p>
<h2>Systemic Examination</h2>
<p><strong>Respiratory:</strong> ${patient.respiratory || '—'}</p>
<p><strong>Abdominal:</strong> ${patient.abdominal || '—'}</p>
<p><strong>CNS/CVS:</strong> ${patient.cnsCvs || '—'}</p>
${dxResult ? `
<h2>Diagnosis</h2>
<p><strong>${dxResult.primary_diagnosis}</strong> <span class="badge badge-${dxResult.confidence}">${dxResult.confidence}</span></p>
<p>${dxResult.diagnosis_reasoning || ''}</p>
${dxResult.differentials?.length ? `<h2>Differentials</h2><table><tr><th>Diagnosis</th><th>Key Feature</th><th>Likelihood</th></tr>${dxResult.differentials.map(d => `<tr><td>${d.diagnosis}</td><td>${d.key_feature}</td><td>${d.likelihood}</td></tr>`).join('')}</table>` : ''}
` : ''}
${txResult ? `
<h2>Treatment Plan</h2>
${txResult.treatment_plan?.map((s, i) => `<p><strong>Step ${i + 1}:</strong> ${s.step} — ${s.details}</p>`).join('') || ''}
<h2>Medications</h2>
<table><tr><th>#</th><th>Drug</th><th>Dose</th><th>Route</th><th>Frequency</th><th>Duration</th></tr>
${txResult.medications?.map((m, i) => `<tr><td>${i + 1}</td><td>${m.drug}</td><td>${m.dose}</td><td>${m.route}</td><td>${m.frequency}</td><td>${m.duration}</td></tr>`).join('') || ''}
</table>
${txResult.monitoring ? `<h2>Monitoring</h2><p>${txResult.monitoring}</p>` : ''}
${txResult.red_flags ? `<h2>Red Flags</h2><p style="color:#dc2626">${txResult.red_flags}</p>` : ''}
` : ''}
<div class="sig"><div class="sig-line"></div><small>${doctor?.name || 'Clinician'}<br>BMDC: ${doctor?.bmdc || '—'}</small></div>
<div class="footer">Generated by ClinIQ Clinical Decision Support | ${new Date().toLocaleString()}</div>
</body></html>`

  win.document.write(html)
  win.document.close()
  setTimeout(() => win.print(), 500)
}

// ─── Referral Letter Generator ───────────────────────────────────────
export function generateReferral(patient, dxResult, txResult, doctor, referTo) {
  const win = window.open('', '_blank', 'width=800,height=1000')
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Referral Letter</title>
<style>
  body { font-family: 'Inter', Arial, sans-serif; color: #111; max-width: 700px; margin: 0 auto; padding: 40px; font-size: 14px; line-height: 1.7; }
  .header { text-align: center; border-bottom: 2px solid #111; padding-bottom: 12px; margin-bottom: 24px; }
  .header h1 { font-size: 20px; margin: 0; }
  .header p { font-size: 12px; color: #666; margin: 4px 0 0; }
  .date { text-align: right; margin-bottom: 20px; font-size: 13px; }
  .sig { margin-top: 50px; }
  .sig-line { border-top: 1px solid #111; width: 200px; margin-bottom: 4px; }
</style></head><body>
<div class="header">
  <h1>REFERRAL LETTER</h1>
  <p>From ${doctor?.name || 'Doctor'} | BMDC: ${doctor?.bmdc || '—'} | ${doctor?.college || ''}</p>
</div>
<div class="date">Date: ${new Date().toLocaleDateString()}</div>
<p>Dear ${referTo || 'Colleague'},</p>
<p>I am writing to refer <strong>${patient.name || 'the patient'}</strong>, ${patient.age || '—'} year old ${patient.sex || ''}, for your expert opinion and further management.</p>
<p><strong>Clinical Summary:</strong><br>
The patient presented with ${patient.complaints || 'the following complaints'}. On examination, vitals showed BP: ${patient.bp || '—'}, Pulse: ${patient.pulse || '—'}/min, Temp: ${patient.temp || '—'}°F, SpO2: ${patient.spo2 || '—'}%.</p>
${patient.pastHistory ? `<p><strong>Relevant History:</strong> ${patient.pastHistory}</p>` : ''}
${patient.drugHistory ? `<p><strong>Current Medications:</strong> ${patient.drugHistory}</p>` : ''}
${dxResult ? `<p><strong>Working Diagnosis:</strong> ${dxResult.primary_diagnosis} (${dxResult.confidence} confidence)</p>
<p><strong>Clinical Reasoning:</strong> ${dxResult.diagnosis_reasoning || ''}</p>` : ''}
${txResult ? `<p><strong>Treatment Given:</strong><br>${txResult.medications?.map(m => `${m.drug} ${m.dose} ${m.frequency}`).join(', ') || 'As per attached prescription'}</p>` : ''}
<p>I would appreciate your valuable opinion regarding further management of this patient.</p>
<p>Thank you.</p>
<div class="sig">
  <div class="sig-line"></div>
  <strong>${doctor?.name || 'Doctor'}</strong><br>
  <small>BMDC: ${doctor?.bmdc || '—'}<br>${doctor?.college || ''}</small>
</div>
</body></html>`
  win.document.write(html)
  win.document.close()
  setTimeout(() => win.print(), 500)
}

// ─── WhatsApp Prescription Share ─────────────────────────────────────
export function shareWhatsApp(patient, dxResult, txResult, doctor) {
  let text = `*Prescription — ${doctor?.name || 'Doctor'}*\n`
  text += `Patient: ${patient.name || '—'}, ${patient.age || '—'}/${patient.sex || '—'}\n`
  text += `Date: ${new Date().toLocaleDateString()}\n`
  if (dxResult) text += `Dx: ${dxResult.primary_diagnosis}\n`
  text += `\n*Rx:*\n`
  txResult?.medications?.forEach((m, i) => {
    text += `${i + 1}. ${m.drug} ${m.dose} — ${m.frequency} x ${m.duration}\n`
  })
  if (txResult?.patient_advice) text += `\n_Advice: ${txResult.patient_advice}_\n`
  text += `\n_Generated by ClinIQ_`
  window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank')
}

// ─── QR Code (simple text-based, uses external API) ──────────────────
export function generatePatientQR(patientId, patientName) {
  const data = JSON.stringify({ id: patientId, name: patientName, app: 'ClinIQ' })
  return `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(data)}`
}
